buildCommand: pip install -r requirements.txt
services:
  - type: web
    name: Immobilier-Smart
    env: python
    buildCommand: ""
    startCommand: python bot.py
    plan: free
    autoDeploy: true
    
