services:
  - type: worker
    name: immobilier-Smart
    runtime: python
    repo: https://github.com/ton-utilisateur/ton-repo.git  # ← à remplacer par ton vrai repo
    branch: main
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: MONGO_URI
        sync: false
      - key: OPENROUTER_KEY
        sync: false
