buildCommand: pip install -r requirements.txt
startCommand: python bot.py
services:
  - type: web
    name: Immobilier-Smart
    env: python
    plan: free
    autoDeploy: true
ports:
      - "8080"  # Port spécifique que vous souhaitez utiliser
